import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../app/components/Header";
import Footer from "../app/components/Footer"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "썰레발-레전드썰,웃긴썰,썰모음집",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <head>
        {/* ✅ 구글 애드센스 승인용 코드 추가 */}
        <meta name="google-adsense-account" content="ca-pub-XXXXXXX" />
        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8968704393078565"
         crossOrigin="anonymous"></script>
      </head>
      <body className="flex flex-col min-h-screen">
  <Header />
  <main className="flex-1 w-full mx-auto">
    {children}
  </main>
  <Footer />
</body>
    </html>
  );
}
